const song = {
    // VERSE 0 --------------------
    0:"poemdrop",
    // 0:"drop",
    8:"poemdrop",
    16:"poemdrop",
    20:"drop",
    28:"poemdrop",
    36:"drop",
    44:"poemdrop",
    49:"drop",
    53:"drop",
    // VERSE 1 --------------------
    60:"poemdrop",
    62:"drop",
    64:"drop",
    66:"drop",
    68:"drop",
    76:"poemdrop",
    78:"drop",
    80:"drop",
    82:"drop",
    84:"drop",
    92:"poemdrop",
    94:"drop",
    96:"drop",
    98:"drop",
    100:"poemdrop",
    104:"drop",
    108:"drop",
    110:"drop",
    112:"drop",
    114:"drop",
    116:"drop",
    120:"poemdrop",
    // VERSE 2 --------------------
    124:"poemdrop",
    128:"drop",
    130:"drop",
    132:"drop",
    140:"poemdrop",
    142:"drop",
    144:"drop",
    146:"drop",
    148:"drop",
    156:"poemdrop",
    158:"drop",
    160:"drop",
    162:"poemdrop",
    164:"drop",
    166:"drop",
    168:"drop",
    172:"drop",
    174:"drop",
    176:"drop",
    178:"drop",
    180:"poemdrop",
    // VERSE 2 --------------------
    186:{
        type:"line-onedir",
        direction:"left",
        count:5,
        qtr_bars:2,
        poem:true
    },
    197:{
        type:"line-onedir",
        direction:"down",
        count:2,
        qtr_bars:1/2
    },
    199:{
        type:"line-onedir",
        direction:"right",
        count:2,
        qtr_bars:1/2
    },
    201:{
        type:"line-onedir",
        direction:"up",
        count:2,
        qtr_bars:1/2
    },
    202:{
        type:"line-onedir",
        direction:"right",
        count:5,
        qtr_bars:2,
        poem:true
    },
    212:{
        type:"line-onedir",
        direction:"down",
        count:2,
        qtr_bars:1/2,
    },
    214:{
        type:"line-onedir",
        direction:"left",
        count:2,
        qtr_bars:1/2
    },
    216:{
        type:"line-onedir",
        direction:"up",
        count:2,
        qtr_bars:1/2
    },
    218:{
        type:"line-onedir",
        direction:"left",
        count:4,
        qtr_bars:2,
        poem:true
    },
    226:{
        type:"line-onedir",
        direction:"right",
        count:4,
        qtr_bars:2,
        poem:true
    },
}
